blank_issues_enabled: false
contact_links:
  - name: ğŸ  Nodejs Express TS Boilerplate
    url: https://github.com/khguruge/nodejs-express-ts-boilerplate
    about: Access our development homebase for additional information about the repository.
